apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    server: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7.27
    env: 
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mysql.root.password
          name: mysql-secret
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          key: mysql.database
          name: mysql-secret
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          key: mysql.user
          name: mysql-secret
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mysql.password
          name: mysql-secret
    ports:
    - name: port
      containerPort: 3306
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m
    livenessProbe:
      tcpSocket:
        port: 3306
      initialDelaySeconds: 100
      failureThreshold: 3
      periodSeconds: 5
      timeoutSeconds: 5
  restartPolicy: Always