apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql.root.password: password
  mysql.database: mysqldb
  mysql.user: my_user
  mysql.password: my_password
  mysql.db.host: mysql-svc