apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    server: wordpress
spec:
  containers:
  - name: wordpress
    image: wordpress:4-php7.0
    ports:
    - name: port
      containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      valueFrom:
        secretKeyRef:
          key: mysql.db.host
          name: mysql-secret
    - name: WORDPRESS_DB_USER
      valueFrom:
        secretKeyRef:
          key: mysql.user
          name: mysql-secret
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mysql.password
          name: mysql-secret
    - name: WORDPRESS_DB_NAME
      valueFrom:
        secretKeyRef:
          key: mysql.database
          name: mysql-secret    
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m
    livenessProbe:
      tcpSocket:
        port: 80  
      initialDelaySeconds: 300
      failureThreshold: 3
      periodSeconds: 3
      timeoutSeconds: 5
  restartPolicy: Always