apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    version: "1"
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: WORDPRESS_DB_HOST
            valueFrom:
              configMapKeyRef:
                key: db_host
                name: mysql-cfgmap
          - name: WORDPRESS_DB_NAME
            valueFrom:
              configMapKeyRef:
                key: db_name
                name: mysql-cfgmap
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: mysql-secret
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: user_passwd
                name: mysql-secret
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mysql
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: init-mysql
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup mysql-svc; do echo waiting for mysql-svc; sleep 2; done;']
