apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
  - port: 8888
    targetPort: 80
  type: LoadBalancer # choose the right type base on your kubernetes environment
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/log/nginx
              name: share-logs
            - mountPath: /etc/nginx/
              name: nginx-conf
              readOnly: true
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
      terminationGracePeriodSeconds: 60
      volumes:
        - name: share-logs
          hostPath:
            path: /var/log/nginx
            type: DirectoryOrCreate
        - configMap:
            items:
              - key: nginx.conf # key name in configmap
                path: nginx.conf # file name in container
            name: nginx-conf
          name: nginx-conf
